"""create tables

Revision ID: 61ce7087604f
Revises: 61923c689dd4
Create Date: 2026-08-06 16:49:15.466370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61ce7087604f'
down_revision: Union[str, Sequence[str], None] = '61923c689dd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deployments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('model_version_id', sa.String(length=36), nullable=False),
    sa.Column('environment', sa.Enum('DEV', 'TEST', 'STAGING', 'PRODUCTION', name='deploymentenvironment'), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'VALIDATING', 'DEPLOYING', 'SUCCEEDED', 'FAILED', 'ROLLED_BACK', name='deploymentstate'), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('failure_reason', sa.String(length=500), nullable=True),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployments_idempotency_key'), 'deployments', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_deployments_model_version_id'), 'deployments', ['model_version_id'], unique=False)
    op.create_table('deployment_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deployment_id', sa.String(length=36), nullable=False),
    sa.Column('event', sa.Enum('DEPLOYMENT_REQUESTED', 'VALIDATION_STARTED', 'DEPLOYMENT_STARTED', 'DEPLOYMENT_COMPLETED', 'APPROVAL_VALIDATION_FAILED', 'RUNTIME_TIMEOUT', 'RETRY_REQUESTED', 'ROLLBACK_STARTED', 'ROLLBACK_COMPLETED', name='deploymentevent'), nullable=False),
    sa.Column('old_status', sa.Enum('REQUESTED', 'VALIDATING', 'DEPLOYING', 'SUCCEEDED', 'FAILED', 'ROLLED_BACK', name='deploymentstate'), nullable=True),
    sa.Column('new_status', sa.Enum('REQUESTED', 'VALIDATING', 'DEPLOYING', 'SUCCEEDED', 'FAILED', 'ROLLED_BACK', name='deploymentstate'), nullable=False),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployment_history_deployment_id'), 'deployment_history', ['deployment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deployment_history_deployment_id'), table_name='deployment_history')
    op.drop_table('deployment_history')
    op.drop_index(op.f('ix_deployments_model_version_id'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_idempotency_key'), table_name='deployments')
    op.drop_table('deployments')
    # ### end Alembic commands ###
